// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: f970808d5ccd1b5d0d1a0ab09d8aefeed08c1d05

package data

// linguist's commit from which files were generated.
var LinguistCommit = "f970808d5ccd1b5d0d1a0ab09d8aefeed08c1d05"
